import { GoogleGenAI } from "@google/genai";
import type { GenerateImageResponse } from "@google/genai";
import { GenerationConfig } from "../types";


/**
 * Generates an image using the Gemini API (imagen-4.0-generate-001 model).
 * @param config The configuration for the image generation.
 * @returns A promise that resolves to the base64 encoded string of the generated image.
 */
export const generateImage = async (config: GenerationConfig): Promise<string> => {
    // Initialize the client. The API key is automatically picked up from the environment.
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

    try {
        const response: GenerateImageResponse = await ai.models.generateImages({
            model: 'imagen-4.0-generate-001',
            prompt: config.prompt,
            config: {
                numberOfImages: 1, // API currently supports 1. Adjust if needed.
                outputMimeType: 'image/jpeg',
                aspectRatio: config.aspectRatio,
            },
        });

        if (response.generatedImages && response.generatedImages.length > 0) {
            const base64ImageBytes: string = response.generatedImages[0].image.imageBytes;
            return `data:image/jpeg;base64,${base64ImageBytes}`;
        } else {
            throw new Error("No image was generated by the API.");
        }
    } catch (error) {
        console.error("Error generating image with Gemini API:", error);
        // You might want to handle specific error types from the API here
        if (error instanceof Error) {
            throw new Error(`Failed to generate image: ${error.message}`);
        }
        throw new Error("Failed to generate image. Please try again later.");
    }
};